/**
 * Generated by orval 🍺
 * Do not edit manually.
 * grupp1.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface AccessTokenResponse {
  /** @nullable */
  tokenType?: string | null;
  accessToken: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expiresIn: number | string;
  refreshToken: string;
}
