/**
 * Generated by orval 🍺
 * Do not edit manually.
 * grupp1.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface InfoRequest {
  /** @nullable */
  newEmail?: string | null;
  /** @nullable */
  newPassword?: string | null;
  /** @nullable */
  oldPassword?: string | null;
}
