/**
 * Generated by orval 🍺
 * Do not edit manually.
 * grupp1.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface TwoFactorResponse {
  sharedKey: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  recoveryCodesLeft: number | string;
  /** @nullable */
  recoveryCodes?: string[] | null;
  isTwoFactorEnabled: boolean;
  isMachineRemembered: boolean;
}
