/**
 * Generated by orval 🍺
 * Do not edit manually.
 * grupp1.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface TwoFactorRequest {
  /** @nullable */
  enable?: boolean | null;
  /** @nullable */
  twoFactorCode?: string | null;
  resetSharedKey?: boolean;
  resetRecoveryCodes?: boolean;
  forgetMachine?: boolean;
}
