/**
 * Generated by orval 🍺
 * Do not edit manually.
 * grupp1.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  AccessTokenResponse,
  ForgotPasswordRequest,
  HttpValidationProblemDetails,
  InfoRequest,
  InfoResponse,
  LoginRequest,
  MapIdentityApiApiConfirmEmailParams,
  PostApiLoginParams,
  RefreshRequest,
  RegisterRequest,
  ResendConfirmationEmailRequest,
  ResetPasswordRequest,
  TwoFactorRequest,
  TwoFactorResponse
} from '../../models';


export type postApiRegisterResponse200 = {
  data: void
  status: 200
}

export type postApiRegisterResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiRegisterResponseSuccess = (postApiRegisterResponse200) & {
  headers: Headers;
};
export type postApiRegisterResponseError = (postApiRegisterResponse400) & {
  headers: Headers;
};

export type postApiRegisterResponse = (postApiRegisterResponseSuccess | postApiRegisterResponseError)

export const getPostApiRegisterUrl = () => {




  return `/api/register`
}

export const postApiRegister = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<postApiRegisterResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiRegisterResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiRegisterResponse
}


export type postApiLoginResponse200 = {
  data: AccessTokenResponse
  status: 200
}

export type postApiLoginResponseSuccess = (postApiLoginResponse200) & {
  headers: Headers;
};
;

export type postApiLoginResponse = (postApiLoginResponseSuccess)

export const getPostApiLoginUrl = (params?: PostApiLoginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/login?${stringifiedParams}` : `/api/login`
}

export const postApiLogin = async (loginRequest: LoginRequest,
    params?: PostApiLoginParams, options?: RequestInit): Promise<postApiLoginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiLoginUrl(params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiLoginResponse
}


export type postApiRefreshResponse200 = {
  data: AccessTokenResponse
  status: 200
}

export type postApiRefreshResponseSuccess = (postApiRefreshResponse200) & {
  headers: Headers;
};
;

export type postApiRefreshResponse = (postApiRefreshResponseSuccess)

export const getPostApiRefreshUrl = () => {




  return `/api/refresh`
}

export const postApiRefresh = async (refreshRequest: RefreshRequest, options?: RequestInit): Promise<postApiRefreshResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(refreshRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiRefreshResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiRefreshResponse
}


export type mapIdentityApiApiConfirmEmailResponse200 = {
  data: void
  status: 200
}

export type mapIdentityApiApiConfirmEmailResponseSuccess = (mapIdentityApiApiConfirmEmailResponse200) & {
  headers: Headers;
};
;

export type mapIdentityApiApiConfirmEmailResponse = (mapIdentityApiApiConfirmEmailResponseSuccess)

export const getMapIdentityApiApiConfirmEmailUrl = (params: MapIdentityApiApiConfirmEmailParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/confirmEmail?${stringifiedParams}` : `/api/confirmEmail`
}

export const mapIdentityApiApiConfirmEmail = async (params: MapIdentityApiApiConfirmEmailParams, options?: RequestInit): Promise<mapIdentityApiApiConfirmEmailResponse> => {

  const res = await fetch(getMapIdentityApiApiConfirmEmailUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: mapIdentityApiApiConfirmEmailResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as mapIdentityApiApiConfirmEmailResponse
}


export type postApiResendConfirmationEmailResponse200 = {
  data: void
  status: 200
}

export type postApiResendConfirmationEmailResponseSuccess = (postApiResendConfirmationEmailResponse200) & {
  headers: Headers;
};
;

export type postApiResendConfirmationEmailResponse = (postApiResendConfirmationEmailResponseSuccess)

export const getPostApiResendConfirmationEmailUrl = () => {




  return `/api/resendConfirmationEmail`
}

export const postApiResendConfirmationEmail = async (resendConfirmationEmailRequest: ResendConfirmationEmailRequest, options?: RequestInit): Promise<postApiResendConfirmationEmailResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiResendConfirmationEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(resendConfirmationEmailRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiResendConfirmationEmailResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiResendConfirmationEmailResponse
}


export type postApiForgotPasswordResponse200 = {
  data: void
  status: 200
}

export type postApiForgotPasswordResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiForgotPasswordResponseSuccess = (postApiForgotPasswordResponse200) & {
  headers: Headers;
};
export type postApiForgotPasswordResponseError = (postApiForgotPasswordResponse400) & {
  headers: Headers;
};

export type postApiForgotPasswordResponse = (postApiForgotPasswordResponseSuccess | postApiForgotPasswordResponseError)

export const getPostApiForgotPasswordUrl = () => {




  return `/api/forgotPassword`
}

export const postApiForgotPassword = async (forgotPasswordRequest: ForgotPasswordRequest, options?: RequestInit): Promise<postApiForgotPasswordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(forgotPasswordRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiForgotPasswordResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiForgotPasswordResponse
}


export type postApiResetPasswordResponse200 = {
  data: void
  status: 200
}

export type postApiResetPasswordResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiResetPasswordResponseSuccess = (postApiResetPasswordResponse200) & {
  headers: Headers;
};
export type postApiResetPasswordResponseError = (postApiResetPasswordResponse400) & {
  headers: Headers;
};

export type postApiResetPasswordResponse = (postApiResetPasswordResponseSuccess | postApiResetPasswordResponseError)

export const getPostApiResetPasswordUrl = () => {




  return `/api/resetPassword`
}

export const postApiResetPassword = async (resetPasswordRequest: ResetPasswordRequest, options?: RequestInit): Promise<postApiResetPasswordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(resetPasswordRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiResetPasswordResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiResetPasswordResponse
}


export type postApiManage2faResponse200 = {
  data: TwoFactorResponse
  status: 200
}

export type postApiManage2faResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiManage2faResponse404 = {
  data: void
  status: 404
}

export type postApiManage2faResponseSuccess = (postApiManage2faResponse200) & {
  headers: Headers;
};
export type postApiManage2faResponseError = (postApiManage2faResponse400 | postApiManage2faResponse404) & {
  headers: Headers;
};

export type postApiManage2faResponse = (postApiManage2faResponseSuccess | postApiManage2faResponseError)

export const getPostApiManage2faUrl = () => {




  return `/api/manage/2fa`
}

export const postApiManage2fa = async (twoFactorRequest: TwoFactorRequest, options?: RequestInit): Promise<postApiManage2faResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiManage2faUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(twoFactorRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiManage2faResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiManage2faResponse
}


export type getApiManageInfoResponse200 = {
  data: InfoResponse
  status: 200
}

export type getApiManageInfoResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type getApiManageInfoResponse404 = {
  data: void
  status: 404
}

export type getApiManageInfoResponseSuccess = (getApiManageInfoResponse200) & {
  headers: Headers;
};
export type getApiManageInfoResponseError = (getApiManageInfoResponse400 | getApiManageInfoResponse404) & {
  headers: Headers;
};

export type getApiManageInfoResponse = (getApiManageInfoResponseSuccess | getApiManageInfoResponseError)

export const getGetApiManageInfoUrl = () => {




  return `/api/manage/info`
}

export const getApiManageInfo = async ( options?: RequestInit): Promise<getApiManageInfoResponse> => {

  const res = await fetch(getGetApiManageInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiManageInfoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiManageInfoResponse
}


export type postApiManageInfoResponse200 = {
  data: InfoResponse
  status: 200
}

export type postApiManageInfoResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type postApiManageInfoResponse404 = {
  data: void
  status: 404
}

export type postApiManageInfoResponseSuccess = (postApiManageInfoResponse200) & {
  headers: Headers;
};
export type postApiManageInfoResponseError = (postApiManageInfoResponse400 | postApiManageInfoResponse404) & {
  headers: Headers;
};

export type postApiManageInfoResponse = (postApiManageInfoResponseSuccess | postApiManageInfoResponseError)

export const getPostApiManageInfoUrl = () => {




  return `/api/manage/info`
}

export const postApiManageInfo = async (infoRequest: InfoRequest, options?: RequestInit): Promise<postApiManageInfoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiManageInfoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(infoRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiManageInfoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiManageInfoResponse
}


